### ISSUE TITLE
Error when using GoogleFinanceSource

### ISSUE THREAD

**Issue by pverspeelt** [mannau/tm.plugin.webmining#21]
Using `GoogleFinanceSource` now returns an error, probably because Google changed the google finance last november. 

```
GoogleFinanceSource("NASDAQ:MSFT")

> StartTag: invalid element name
> Extra content at the end of the document
> Error: 1: StartTag: invalid element name
> 2: Extra content at the end of the document

```
I'm trying to figure out an alternative, for now `YahooFinanceSource` still works

**Comment by krvtch** [comment]
I also get the same error when I use the default ie encoding method (utf-8). So I tried to change the default ie encoding method to ansi, example below:

```
WebCorpus(GoogleFinanceSource("NASDAQ:MSFT", params = list(hl = "en", q = "NASDAQ:MSFT", ie = "ansi", start = 0, num = 20, output = "rss")))
```

The above line was successful at first but when I try the exact same line of code twice it's showing back the original error. So I tried again to change to "utf16" this time. Same issue, works at first try but error on the second.

```
WebCorpus(GoogleFinanceSource("NASDAQ:MSFT", params = list(hl = "en", q = "NASDAQ:MSFT", ie = "ansi", start = 0, num = 20, output = "rss")))
```

**Comment by icezerowjj** [comment]
I also encounter this issue. Has it been fixed yet?

**Comment by pverspeelt** [comment]
The fix I proposed is not working anymore. Google has discontinued finance.google.com.

**Comment by ddten** [comment]
Check this file-
R/source.R 
should work now

**Comment by R-Squire** [comment]
is anyone else having trouble with WebCorpus function not working?

**Comment by KabuziwaDominki** [comment]
Hello, I also have problems with WebCorpus and cannot work with Sources of tm.plugin.webmining in general. Does someone have a solution or an alternative way?

**Comment by BenceToth** [comment]
Hi, it seems like the issue is still ongoing. Is the tm.plugin.webmining package still supported?

**Comment by KabuziwaDominki** [comment]
Hello. The problem ist not the package itsself but the fact, that Google and yahoo stopped their service. If you want to work with the package using financial use, I recommend to work with Reuters
